CREATE DATABASE IF NOT EXISTS obsdl DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE obsdl;

CREATE TABLE IF NOT EXISTS download_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    bucket VARCHAR(128) NOT NULL,
    object_key VARCHAR(512) NOT NULL,
    concurrency INT NOT NULL DEFAULT 4,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
